# Generated by Django 5.0.3 on 2024-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=50)),
                ('ln', models.CharField(max_length=50)),
                ('tech', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
